### ISSUE TITLE
Incompatible with BetterThirdPerson-Forge-1.18-1.6.0

### ISSUE THREAD

**Issue by PaulerLeOne** [BunnyCinnamon/OffHandCombat#11]
off-hand-combat-0.0.0-forge and architectury-3.6.16
When lauching the game with these mods, it turns back to the launcher giving error 0, the loading window doesn't even appear.

**Comment by BunnyCinnamon** [comment]
Oh hmmm I will try to fix it...

**Comment by PaulerLeOne** [comment]
https://paste.gg/p/anonymous/e421551fcfc94146985a061ff899400e
Here's a log btw.

**Comment by BunnyCinnamon** [comment]
fixed I think
