### ISSUE TITLE
Hand animations are choppy

### ISSUE THREAD

**Issue by PaulerLeOne** [BunnyCinnamon/OffHandCombat#14]
off-hand-combat-0.0.1-forge and architectury-3.6.17
All the hand animations in first person, like attacking, placing a block or breaking a block, look choppy and not fliud.

**Comment by BunnyCinnamon** [comment]
Oh shit I thought I was tripping, aight thanks

**Comment by Camawama** [comment]
LOL!

**Comment by Camawama** [comment]
The hand animations still seem a bit choppy. What would be causing this?
