### ISSUE TITLE
I am testing the Fabric Version of the Mod.

### ISSUE THREAD

**Issue by Camawama** [BunnyCinnamon/OffHandCombat#15]
For some reason, only version 0.0.0 is being shown in the CurseForge Launcher. When I manually install the 0.0.1 update, it shows an error icon saying it isn't supported. The 0.0.1 version also requires the Architectury API for some reason now.

Another issue I have noticed, when holding down the RIGHT CLICK button, the sword continuously swings really fast. It is somewhat game-breaking.

Also, when holding a sword in the off-hand in creative mode and attempting to interact/place blocks, nothing works.

I love this mod a lot, but I am going to wait for the bugs to be fixed before I add it to the Fabric Version of my Modpack. I will do further testing with the Forge Version later!

**Comment by BunnyCinnamon** [comment]
Thancc
