### ISSUE TITLE
Interacting with blocks using offhand

### ISSUE THREAD

**Issue by qualterz** [BunnyCinnamon/OffHandCombat#16]
Suggest adding the ability to use tools with offhand. For example, if i have in offhand a hoe, this feature allows me to use the hoe in various modes so that i can break blocks with it and use it for plowing.

**Comment by BunnyCinnamon** [comment]
Mmmmm sure but you can swap tools with the F key already so I don't know tbh

will it only apply if the main hand is empty?
because if you're holding two pickaxes How will it decide what tool to use? 

I'm thinking that it could work but only if the main hand is empty.
