### ISSUE TITLE
Swing animations still choppy

### ISSUE THREAD

**Issue by PaulerLeOne** [BunnyCinnamon/OffHandCombat#17]
This issue was already submitted and closed, but the problem still remains in 0.0.2.

**Comment by BunnyCinnamon** [comment]
Fabric?

**Comment by PaulerLeOne** [comment]
Forge

**Comment by BunnyCinnamon** [comment]
Oh did you re download the file?

**Comment by BunnyCinnamon** [comment]
Oh nvm I checked and its still choppy lol thank you, will upload a new file
