### ISSUE TITLE
Incompatible Datapack(s)

### ISSUE THREAD

**Issue by Coraline77447** [BunnyCinnamon/OffHandCombat#4]
Hi. Remember me from my last two issue reports? Well I'm here to report yet another issue regarding datapacks with your mod and why I'm reporting this about it's datapack(s) is cause I'm sick and tired of losing my worlds due to incomplete or missing data within the datapacks or outdated datapacks of some of the mods that I'm playing with which at some point I lose the world that I would be playing on and how I know this is cause when making a new world you can apply datapacks except for datapacks that mods adds, when I look in there I see some red ones that when I hover my mouse over them they say "Incompatible, made for an older version of Minecraft." When I would try to load into a modded world I get a message that says that the selected datapacks have errors and asks me to either enter safe mode (which I can't enter safe mode) or go to title screen and in the message it says that I can manually fix them which Idk how to fix incomplete, missing, outdated, or even broken datapacks to mods that has these errors....

**Comment by ArekkuusuJerii** [comment]
oh oof, I don't know how that happens

**Comment by Coraline77447** [comment]
"Idk how to fix incomplete, missing, outdated, or even broken datapacks to mods that has these errors...."

I know how to fix incompatible datapacks now, I simply just go to the mod's mc.packmeta file and change what its pack_format version is currently set to to 6 even tho I shouldn't be the one to do that but some mod owners either forget to do that or are too lazy to do that.

I'm not sayin that you're being too lazy to update your mod's datapack version and I'm not blaming you for forgetting to update your mod's datapack version.

I was just tryin to kindly tell ya to update it or was trying to kindly remind ya to do that, okay. Keep up the good work and I'm loving the mod so far.
