### ISSUE TITLE
[1.16.5] Client Crash | [Wardance mod incompatiblity] Critical injection failure: Redirector tickHand

### ISSUE THREAD

**Issue by Cixon** [BunnyCinnamon/OffHandCombat#5]
Using latest version. -> _(v3.2.0.3)_
Using Forge version. -> _(36.0.42)_
Using Mixing Bootstrap version. -> _v1.0.5_

[crash-2021-03-05_15.15.43-client.txt](https://github.com/BunnyCinnamon/OffHandCombat/files/6093433/crash-2021-03-05_15.15.43-client.txt)
[latest.log](https://github.com/BunnyCinnamon/OffHandCombat/files/6093434/latest.log) **Line 51.**

**Comment by Cixon** [comment]
Addition context: I was using a mod called [Project: War Dance](https://www.curseforge.com/minecraft/mc-mods/project-war-dance), this could have caused the OffHandCombat to throw error, maybe not?

This mod recreates vanillas combat system from the ground up.

**Comment by BunnyCinnamon** [comment]
That is because that mod is overriding the offhand modifications I do to the game, as long as that happens the mods will be incompatible

**Comment by BunnyCinnamon** [comment]
The only solutions is either of us completely overrides interfering changes, and it's possible it'll start an arms race.

**Comment by BunnyCinnamon** [comment]
A solution I'd prefer (but might not happen) is they remove the offhand aspect of the mod, since what they do is also not entirely correct, and add this mod as an optional dependency.

> They could leave the attack speed game modifications unchanged, that was done correctly enough I believe.

yeah

**Comment by Cixon** [comment]
> > They could leave the attack speed game modifications unchanged, that was done correctly enough I believe.
> 

This would be enough?

**Comment by BunnyCinnamon** [comment]
Yeah they just have to remove the offhand attack from their mod.

**Comment by Jackiecrazy** [comment]
Why is it not quite correct? The original offhand attack function of PWD came from its predecessor, Taoism, so I know the current function is extremely hacky. I can remove it, but I'd like to know how I can improve for the future.

**Comment by BunnyCinnamon** [comment]
Oh no nvm, I assumed you were doing it the wrong way by copy pasting the attack logic for the offhand because you mention an offhand attack event, but you actually swap the items and apply the attributes like should be. You're good Sorry :<

**Comment by BunnyCinnamon** [comment]
I'd say just copy what I do in this mod add a incompatibility warning so people don't install this by mistake.

**Comment by Cixon** [comment]
i-
so, huh?

**Comment by BunnyCinnamon** [comment]
ah oops, so Project:War Dance mod already adds off hand attacks, you don't need to install this mod
