### ISSUE TITLE
Unable to eat while weapon is in off hand

### ISSUE THREAD

**Issue by Kutomi1** [BunnyCinnamon/OffHandCombat#9]
It's kind of annoying that you have to switch your food to your off hand and your off hand weapon to your main hand when trying to eat while dual wielding. I think it would be really useful if you could eat while a weapon is in your off hand. This is the only problem I found about this mod.

**Comment by BunnyCinnamon** [comment]
Agreed

**Comment by shinefield** [comment]
> Agreed

need 1.12version
